In [4]:
import torch
import numpy as np

In [5]:
x = torch.rand(3,2,5)   # random tensor
y = torch.ones(2,2, dtype = torch.int)
z = torch.empty(3,5)
p = torch.empty(1)
print(y)
print(x.size())
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.Size([3, 2, 5])
torch.float32


In [6]:
l = torch.tensor([2.5 , 3]) # from python list
print(l)
print(l.dtype)

tensor([2.5000, 3.0000])
torch.float32


In [7]:
# Basic operations
y = torch.rand(2,2)
x = torch.rand(2,2)
z = x + y  # x = torch.add(), torch.sub(), torch.mul(), torch.div()
print(z)

# inplace addition
y.add_(x)   # any function having trailing underscore will do inplace operation ex sub_, mul_ etc
print(y)

tensor([[1.1980, 0.9021],
        [1.3565, 0.9137]])
tensor([[1.1980, 0.9021],
        [1.3565, 0.9137]])


In [8]:
# slicing

x = torch.rand(5,3)
print(x)
print(x[: , 0])   # all rows and column zero
print(x[1 , :])   # all columns and one row
print(x[1,1])    # one element in tensor

print(x[1,1].item())  # one element

tensor([[0.0154, 0.9681, 0.9832],
        [0.2145, 0.7299, 0.9806],
        [0.6615, 0.1212, 0.7615],
        [0.4675, 0.7411, 0.3059],
        [0.5748, 0.5364, 0.9504]])
tensor([0.0154, 0.2145, 0.6615, 0.4675, 0.5748])
tensor([0.2145, 0.7299, 0.9806])
tensor(0.7299)
0.7299352884292603


In [9]:
# reshaping
x = torch.rand(4,4)
print(x)
y = x.view(16)  # 1-d tesor  (remember the number of elements should be same)
print(y)

c= x.view(-1, 8)
print(c.size())

r = x.view(8,-1)
print(r.size())

tensor([[0.7372, 0.6610, 0.3410, 0.6119],
        [0.7034, 0.2622, 0.6907, 0.3836],
        [0.4720, 0.7037, 0.9104, 0.8861],
        [0.2167, 0.7613, 0.0472, 0.8245]])
tensor([0.7372, 0.6610, 0.3410, 0.6119, 0.7034, 0.2622, 0.6907, 0.3836, 0.4720,
        0.7037, 0.9104, 0.8861, 0.2167, 0.7613, 0.0472, 0.8245])
torch.Size([2, 8])
torch.Size([8, 2])


In [10]:
# from numpy to torch and vice - versa
a = torch.ones(5)
print(a)
b= a.numpy()                     
print(b)
print(type(b))


# both share same memory if they are in cpu

a.add_(1)
print(a)
print(b)

a = np.ones(5)
b = torch.from_numpy(a)      # both share same memory if they are in cpu
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
<class 'torch.Tensor'>


In [11]:
# Gradients using  Auto-grad package

x = torch.randn(3, requires_grad = True)   # requires_grad is required to find grds in future with respect to x
print(x)


# Forward Pass

y = x + 2     # creates a computational graph
print(y)

z = y * y * 2
print(z)
z = z.mean()
print(z)


# To find gradients
z.backward()              #   dz/dx
print(x.grad)             # z = (2(x11 + 2)** 2 + 2(x12 + 2**2) + 2(x13 + 2)**2) * 3


tensor([-0.1111, -0.2704, -0.9136], requires_grad=True)
tensor([1.8889, 1.7296, 1.0864], grad_fn=<AddBackward0>)
tensor([7.1361, 5.9832, 2.3604], grad_fn=<MulBackward0>)
tensor(5.1599, grad_fn=<MeanBackward0>)
tensor([2.5186, 2.3062, 1.4485])


In [12]:
x = torch.randn(3 , requires_grad = True)
print(x)
x.requires_grad_(False)
print(x)

# other option include
# x.detach()  --- not inplace
# with torch.no_grad():

tensor([ 0.3267, -0.9548,  0.4427], requires_grad=True)
tensor([ 0.3267, -0.9548,  0.4427])


In [13]:
# Example of forward pass

weights = torch.ones(4, requires_grad = True)

for epoch in range(4):
    model_output = (weights * 3).sum()
    model_output.backward()                     # ccomputes dm/dw
    print(weights.grad)
    weights.grad.zero_()                        # imp step need to make gradients zero

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [14]:
#  backward propagation


# step 1 --  Forward Pass : Compute Loss
# step 2 --  Compute LOcal gradients at each node
# step 3 --  Backward PAss : Compute dLoss/ dWeights using chain rule

In [15]:
# Example

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)

# forward pass

y_hat = (w * x)
loss = (y_hat - y)**2

print(loss)

# backward
loss.backward()
print(w.grad)                    # if possible try on a paper

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [16]:
# Linear Regression using Autograd

# step -1

# Prediction -- Manual
# Gradient Computation - Manual
# Loss COmputation -MAnual
# Parameter updates : Manual



In [17]:
# Step-1 witout the library


X = np.array([1,2,3,4], dtype = np.float32)
Y = np.array([2,4,6,8], dtype = np.float32)

w = 0.0

# model prediction

def forward(x):
    return w * x

#loss = MSE

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()
    
#gradient
# MSE =  1 /N * (w*x - y)**2
# dj/dw = 1/N * (2x) * (w*x - y)

def gradient(x,y, y_pred):
    return np.dot(2*x , y_pred-y).mean()

print(f'prediction before training : f(5) = {forward(5):.3f}')

# TRaining 
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction
    y_pred = forward(X)
    
    #loss 
    l = loss(Y, y_pred)
    
    # gradients
    dw = gradient(X,Y,y_pred)
    
    #update weights
    w -= learning_rate * dw
    
    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f} , loss ={l:.8f}')

        
print(f'prediction after training : f(5) = {forward(5):.3f}')

prediction before training : f(5) = 0.000
epoch 1: w = 1.200 , loss =30.00000000
epoch 3: w = 1.872 , loss =0.76800019
epoch 5: w = 1.980 , loss =0.01966083
epoch 7: w = 1.997 , loss =0.00050332
epoch 9: w = 1.999 , loss =0.00001288
epoch 11: w = 2.000 , loss =0.00000033
epoch 13: w = 2.000 , loss =0.00000001
epoch 15: w = 2.000 , loss =0.00000000
epoch 17: w = 2.000 , loss =0.00000000
epoch 19: w = 2.000 , loss =0.00000000
prediction after training : f(5) = 10.000


In [18]:
# Step -2

# Prediction -- Manual
# Gradient Computation - Auto GRad
# Loss COmputation -MAnual
# Parameter updates : Manual


In [19]:
# step -- 2 using autograd

X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

# model prediction

def forward(x):
    return w * x

#loss = MSE

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()
    

print(f'prediction before training : f(5) = {forward(5):.3f}')

# TRaining 
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction
    y_pred = forward(X)
    
    #loss 
    l = loss(Y, y_pred)
    
    # gradients = backward pass
    l.backward()    # dl/dw
   
    
    #update weights
    with torch.no_grad():
          w -= learning_rate * w.grad
  
    # zero gradients
    w.grad.zero_()
    
    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f} , loss ={l:.8f}')

        
print(f'prediction after training : f(5) = {forward(5):.3f}')


prediction before training : f(5) = 0.000
epoch 1: w = 0.300 , loss =30.00000000
epoch 11: w = 1.665 , loss =1.16278565
epoch 21: w = 1.934 , loss =0.04506890
epoch 31: w = 1.987 , loss =0.00174685
epoch 41: w = 1.997 , loss =0.00006770
epoch 51: w = 1.999 , loss =0.00000262
epoch 61: w = 2.000 , loss =0.00000010
epoch 71: w = 2.000 , loss =0.00000000
epoch 81: w = 2.000 , loss =0.00000000
epoch 91: w = 2.000 , loss =0.00000000
prediction after training : f(5) = 10.000


In [20]:
# Step -3

# Prediction -- Manual
# Gradient Computation - Auto GRad
# Loss COmputation - Pytorch Loss
# Parameter updates : Pytorch Optimizer

In [21]:
# 1) Design MOdel (input,output, forward Pass)
# 2) Construct Loss and Optimizer
# 3) Training loop
#    - forward pass : computer prediction
#    - backward pass : gradients
#    - update weights

In [22]:
import torch.nn as nn

X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

# model prediction

def forward(x):
    return w * x


print(f'prediction before training : f(5) = {forward(5):.3f}')

# TRaining 
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w] , lr = learning_rate)

for epoch in range(n_iters):
    # prediction
    y_pred = forward(X)
    
    #loss 
    l = loss(Y, y_pred)
    
    # gradients = backward pass
    l.backward()    # dl/dw
   
    
    #update weights
    optimizer.step()
  
    # zero gradients
    optimizer.zero_grad()
    
    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f} , loss ={l:.8f}')

        
print(f'prediction after training : f(5) = {forward(5):.3f}')


prediction before training : f(5) = 0.000
epoch 1: w = 0.300 , loss =30.00000000
epoch 11: w = 1.665 , loss =1.16278565
epoch 21: w = 1.934 , loss =0.04506890
epoch 31: w = 1.987 , loss =0.00174685
epoch 41: w = 1.997 , loss =0.00006770
epoch 51: w = 1.999 , loss =0.00000262
epoch 61: w = 2.000 , loss =0.00000010
epoch 71: w = 2.000 , loss =0.00000000
epoch 81: w = 2.000 , loss =0.00000000
epoch 91: w = 2.000 , loss =0.00000000
prediction after training : f(5) = 10.000


In [23]:
# Step -4

# Prediction -- Pytorch Model
# Gradient Computation - Auto GRad
# Loss COmputation - Pytorch Loss
# Parameter updates : Pytorch Optimizer

In [25]:
import torch.nn as nn

X = torch.tensor([[1],[2],[3],[4]], dtype = torch.float32)       # shape changes
Y = torch.tensor([[2],[4],[6],[8]], dtype = torch.float32)

x_test = torch.tensor([5], dtype = torch.float32)

n_samples, n_features = X.shape
input_size = n_features
output_size = n_features

model = nn.Linear(input_size, output_size)


print(f'prediction before training : f(5) = {model(x_test).item():.3f}')

# TRaining 
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters() , lr = learning_rate)

for epoch in range(n_iters):
    # prediction
    y_pred = model(X)
    
    #loss 
    l = loss(Y, y_pred)
    
    # gradients = backward pass
    l.backward()    # dl/dw
   
    
    #update weights
    optimizer.step()
  
    # zero gradients
    optimizer.zero_grad()
    
    if epoch % 10 == 0:
        [w, b] = model.parameters()
        print(f'epoch {epoch+1}: w = {w[0][0].item():.3f} , loss ={l:.8f}')

        
print(f'prediction after training : f(5) = {model(x_test).item():.3f}')


prediction before training : f(5) = -2.244
epoch 1: w = -0.235 , loss =41.70269775
epoch 11: w = 1.252 , loss =1.38504314
epoch 21: w = 1.503 , loss =0.32411256
epoch 31: w = 1.554 , loss =0.27988422
epoch 41: w = 1.573 , loss =0.26293749
epoch 51: w = 1.587 , loss =0.24761605
epoch 61: w = 1.599 , loss =0.23320317
epoch 71: w = 1.611 , loss =0.21962936
epoch 81: w = 1.623 , loss =0.20684572
epoch 91: w = 1.634 , loss =0.19480634
prediction after training : f(5) = 9.266
